/*
	VZ Enhanced 56K is a caller ID notifier that can block phone calls.
	Copyright (C) 2013-2019 Eric Kutcher

	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef _STRING_TABLES_H
#define _STRING_TABLES_H

// Values with ":", "&", or "-" are replaced with _
// Values with "..." are replaced with ___ 
// Values with # are replaced with NUM
// Keep the defines case sensitive.
// Try to keep them in order.

extern wchar_t *month_string_table[];
extern wchar_t *day_string_table[];

extern wchar_t *common_message_string_table[];

//#define ST_PROMPT_new_version					common_message_string_table[ 0 ]
#define ST_PROMPT_remove_entries				common_message_string_table[ 0 ]
#define ST_PROMPT_remove_entries_contact_list	common_message_string_table[ 1 ]
#define ST_PROMPT_remove_entries_acid			common_message_string_table[ 2 ]
#define ST_PROMPT_remove_entries_apn			common_message_string_table[ 3 ]
#define ST_PROMPT_remove_entries_icid			common_message_string_table[ 4 ]
#define ST_PROMPT_remove_entries_ipn			common_message_string_table[ 5 ]
//#define ST_restricted_area_code					common_message_string_table[ 6 ]
#define ST_cid_already_in_allow_cid_list		common_message_string_table[ 6 ]
#define ST_cid_already_in_ignore_cid_list		common_message_string_table[ 7 ]
#define ST_already_in_contact_list				common_message_string_table[ 8 ]
#define ST_No_modem_found						common_message_string_table[ 9 ]
#define ST_already_in_allow_list				common_message_string_table[ 10 ]
#define ST_already_in_ignore_list				common_message_string_table[ 11 ]
#define ST_enter_valid_caller_id				common_message_string_table[ 12 ]
#define ST_enter_valid_phone_number				common_message_string_table[ 13 ]
#define ST_PROMPT_Popup_windows_and_ringtones	common_message_string_table[ 14 ]
#define ST_PROMPT_Ringtones						common_message_string_table[ 15 ]
#define ST_error_while_saving_settings			common_message_string_table[ 16 ]
#define ST_remove_from_allow_caller_id_list		common_message_string_table[ 17 ]
#define ST_remove_from_allow_phone_number_list	common_message_string_table[ 18 ]
#define ST_remove_from_ignore_caller_id_list	common_message_string_table[ 19 ]
#define ST_remove_from_ignore_phone_number_list	common_message_string_table[ 20 ]
#define ST_PROMPT_download_failed				common_message_string_table[ 21 ]
#define ST_File_format_is_incorrect				common_message_string_table[ 22 ]
//#define ST_Message_Log_still_running			common_message_string_table[ 23 ]
#define ST_Modem_features						common_message_string_table[ 23 ]
#define ST_PROMPT_update_check_failed			common_message_string_table[ 24 ]
#define ST_TreeView_leak						common_message_string_table[ 25 ]
#define ST_Voice_playback_is_not_supported		common_message_string_table[ 26 ]
//#define ST_VZ_Enhanced_56K_is_up_to_date		common_message_string_table[ 27 ]
#define ST_must_restart_program					common_message_string_table[ 27 ]

extern wchar_t *call_log_string_table[];

#define ST_CLL_NUM								call_log_string_table[ 0 ]
#define ST_CLL_Caller_ID_Name					call_log_string_table[ 1 ]
#define ST_CLL_Date_and_Time					call_log_string_table[ 2 ]
#define ST_CLL_Ignore_Caller_ID_Name			call_log_string_table[ 3 ]
#define ST_CLL_Ignore_Phone_Number				call_log_string_table[ 4 ]
#define ST_CLL_Phone_Number						call_log_string_table[ 5 ]

extern wchar_t *contact_list_string_table[];

#define ST_CL_NUM								contact_list_string_table[ 0 ]
#define ST_CL_Cell_Phone_Number					contact_list_string_table[ 1 ]
#define ST_CL_Company							contact_list_string_table[ 2 ]
#define ST_CL_Department						contact_list_string_table[ 3 ]
#define ST_CL_Email_Address						contact_list_string_table[ 4 ]
#define ST_CL_Fax_Number						contact_list_string_table[ 5 ]
#define ST_CL_First_Name						contact_list_string_table[ 6 ]
#define ST_CL_Home_Phone_Number					contact_list_string_table[ 7 ]
#define ST_CL_Job_Title							contact_list_string_table[ 8 ]
#define ST_CL_Last_Name							contact_list_string_table[ 9 ]
#define ST_CL_Nickname							contact_list_string_table[ 10 ]
#define ST_CL_Office_Phone_Number				contact_list_string_table[ 11 ]
#define ST_CL_Other_Phone_Number				contact_list_string_table[ 12 ]
#define ST_CL_Profession						contact_list_string_table[ 13 ]
#define ST_CL_Title								contact_list_string_table[ 14 ]
#define ST_CL_Web_Page							contact_list_string_table[ 15 ]
#define ST_CL_Work_Phone_Number					contact_list_string_table[ 16 ]

extern wchar_t *allow_ignore_list_string_table[];

#define ST_IL_NUM								allow_ignore_list_string_table[ 0 ]
#define ST_IL_Last_Called						allow_ignore_list_string_table[ 1 ]
#define ST_IL_Phone_Number						allow_ignore_list_string_table[ 2 ]
#define ST_IL_Total_Calls						allow_ignore_list_string_table[ 3 ]

extern wchar_t *allow_ignore_cid_list_string_table[];

#define ST_ICIDL_NUM							allow_ignore_cid_list_string_table[ 0 ]
#define ST_ICIDL_Caller_ID_Name					allow_ignore_cid_list_string_table[ 1 ]
#define ST_ICIDL_Last_Called					allow_ignore_cid_list_string_table[ 2 ]
#define ST_ICIDL_Match_Case						allow_ignore_cid_list_string_table[ 3 ]
#define ST_ICIDL_Match_Whole_Word				allow_ignore_cid_list_string_table[ 4 ]
#define ST_ICIDL_Regular_Expression				allow_ignore_cid_list_string_table[ 5 ]
#define ST_ICIDL_Total_Calls					allow_ignore_cid_list_string_table[ 6 ]

extern wchar_t *message_log_list_string_table[];

#define ST_MLL_NUM								message_log_list_string_table[ 0 ]
#define ST_MLL_Date_and_Time_UTC				message_log_list_string_table[ 1 ]
#define ST_MLL_Level							message_log_list_string_table[ 2 ]
#define ST_MLL_Message							message_log_list_string_table[ 3 ]


extern wchar_t *search_string_table[];

#define ST_Search_All							search_string_table[ 0 ]
#define ST_Search_for_							search_string_table[ 1 ]
#define ST_Search_Next							search_string_table[ 2 ]
#define ST_Search_Type							search_string_table[ 3 ]

extern wchar_t *common_string_table[];

#define ST__multiple_caller_ID_names_			common_string_table[ 0 ]
#define ST__multiple_phone_numbers_				common_string_table[ 1 ]
#define ST_Allow_Caller_ID_Name					common_string_table[ 2 ]
#define ST_Allow_Lists							common_string_table[ 3 ]
#define ST_Allow_Phone_Number					common_string_table[ 4 ]
#define ST_Call_Log								common_string_table[ 5 ]
#define ST_Caller_ID_Name						common_string_table[ 6 ]
#define ST_Caller_ID_Names						common_string_table[ 7 ]
#define ST_Caller_ID_Name_						common_string_table[ 8 ]
#define ST_Clear_Message_Log					common_string_table[ 9 ]
#define ST_Close								common_string_table[ 10 ]
#define ST_Contact_Information					common_string_table[ 11 ]
#define ST_Contact_List							common_string_table[ 12 ]
#define ST_Entry_NUM							common_string_table[ 13 ]
#define ST_Export								common_string_table[ 14 ]
#define ST_Ignore_Caller_ID_Name				common_string_table[ 15 ]
#define ST_Ignore_Lists							common_string_table[ 16 ]
#define ST_Ignore_Phone_Number					common_string_table[ 17 ]
#define ST_Import								common_string_table[ 18 ]
#define ST_Last_Called							common_string_table[ 19 ]
#define ST_Match_case							common_string_table[ 20 ]
#define ST_Match_whole_word						common_string_table[ 21 ]
#define ST_Message_Log							common_string_table[ 22 ]
#define ST_No									common_string_table[ 23 ]
#define ST_OK									common_string_table[ 24 ]
#define ST_Options								common_string_table[ 25 ]
#define ST_Phone_Number							common_string_table[ 26 ]
#define ST_Phone_Numbers						common_string_table[ 27 ]
#define ST_Phone_Number_						common_string_table[ 28 ]
#define ST_Regular_expression					common_string_table[ 29 ]
#define ST_Save_Call_Log						common_string_table[ 30 ]
#define ST_Save_Message_Log___					common_string_table[ 31 ]
#define ST_Save_Message_Log						common_string_table[ 32 ]
#define ST_Search								common_string_table[ 33 ]
#define ST_Select_Columns						common_string_table[ 34 ]
#define ST_Time									common_string_table[ 35 ]
#define ST_Total_Calls							common_string_table[ 36 ]
#define ST_Update_Phone_Number					common_string_table[ 37 ]
#define ST_Update_Caller_ID_Name				common_string_table[ 38 ]
#define ST_Yes									common_string_table[ 39 ]

extern wchar_t *contact_string_table[];

#define ST_Add_Contact							contact_string_table[ 0 ]
#define ST_Cell_Phone_							contact_string_table[ 1 ]
#define ST_Choose_File___						contact_string_table[ 2 ]
#define ST_Company_								contact_string_table[ 3 ]
#define ST_Contact_Picture						contact_string_table[ 4 ]
#define ST_Contact_Picture_						contact_string_table[ 5 ]
#define ST_Department_							contact_string_table[ 6 ]
#define ST_Email_Address_						contact_string_table[ 7 ]
#define ST_Fax_									contact_string_table[ 8 ]
#define ST_First_Name_							contact_string_table[ 9 ]
#define ST_Home_Phone_							contact_string_table[ 10 ]
#define ST_Job_Title_							contact_string_table[ 11 ]
#define ST_Last_Name_							contact_string_table[ 12 ]
#define ST_Nickname_							contact_string_table[ 13 ]
#define ST_Office_Phone_						contact_string_table[ 14 ]
#define ST_Other_Phone_							contact_string_table[ 15 ]
#define ST_Play									contact_string_table[ 16 ]
#define ST_Profession_							contact_string_table[ 17 ]
#define ST_Remove_Picture						contact_string_table[ 18 ]
#define ST_Ringtone_							contact_string_table[ 19 ]
#define ST_Stop									contact_string_table[ 20 ]
#define ST_Title_								contact_string_table[ 21 ]
#define ST_Update_Contact						contact_string_table[ 22 ]
#define ST_Web_Page_							contact_string_table[ 23 ]
#define ST_Work_Phone_							contact_string_table[ 24 ]

extern wchar_t *menu_string_table[];

#define ST__About								menu_string_table[ 0 ]
#define ST__Edit								menu_string_table[ 1 ]
#define ST__File								menu_string_table[ 2 ]
#define ST__Help								menu_string_table[ 3 ]
#define ST__Options___							menu_string_table[ 4 ]
#define ST__Save_Call_Log___					menu_string_table[ 5 ]
#define ST__Search___							menu_string_table[ 6 ]
#define ST__Tools								menu_string_table[ 7 ]
#define ST__View								menu_string_table[ 8 ]
#define ST_Add_Contact___						menu_string_table[ 9 ]
#define ST_Add_to_Allow_Caller_ID_Name_List___	menu_string_table[ 10 ]
#define ST_Add_to_Allow_Phone_Number_List		menu_string_table[ 11 ]
#define ST_Add_to_Allow_Phone_Number_List___	menu_string_table[ 12 ]
#define ST_Add_to_Ignore_Caller_ID_Name_List___	menu_string_table[ 13 ]
#define ST_Add_to_Ignore_Phone_Number_List		menu_string_table[ 14 ]
#define ST_Add_to_Ignore_Phone_Number_List___	menu_string_table[ 15 ]
#define ST_Allow_and_Ignore_Lists				menu_string_table[ 16 ]
#define ST_Cancel_Import						menu_string_table[ 17 ]
//#define ST_Cancel_Update_Download				menu_string_table[ 18 ]
#define ST_Check_for__Updates					menu_string_table[ 18 ]
#define ST_Close_Tab							menu_string_table[ 19 ]
#define ST_Contacts								menu_string_table[ 20 ]
#define ST_Copy_Allow_Caller_ID_Name_State		menu_string_table[ 21 ]
#define ST_Copy_Allow_Caller_ID_Name_States		menu_string_table[ 22 ]
#define ST_Copy_Allow_Phone_Number_State		menu_string_table[ 23 ]
#define ST_Copy_Allow_Phone_Number_States		menu_string_table[ 24 ]
#define ST_Copy_Caller_ID_Name					menu_string_table[ 25 ]
#define ST_Copy_Caller_ID_Names					menu_string_table[ 26 ]
#define ST_Copy_Cell_Phone_Number				menu_string_table[ 27 ]
#define ST_Copy_Cell_Phone_Numbers				menu_string_table[ 28 ]
#define ST_Copy_Companies						menu_string_table[ 29 ]
#define ST_Copy_Company							menu_string_table[ 30 ]
#define ST_Copy_Date_and_Time					menu_string_table[ 31 ]
#define ST_Copy_Dates_and_Times					menu_string_table[ 32 ]
#define ST_Copy_Department						menu_string_table[ 33 ]
#define ST_Copy_Departments						menu_string_table[ 34 ]
#define ST_Copy_Email_Address					menu_string_table[ 35 ]
#define ST_Copy_Email_Addresses					menu_string_table[ 36 ]
#define ST_Copy_Fax_Number						menu_string_table[ 37 ]
#define ST_Copy_Fax_Numbers						menu_string_table[ 38 ]
#define ST_Copy_First_Name						menu_string_table[ 39 ]
#define ST_Copy_First_Names						menu_string_table[ 40 ]
#define ST_Copy_Home_Phone_Number				menu_string_table[ 41 ]
#define ST_Copy_Home_Phone_Numbers				menu_string_table[ 42 ]
#define ST_Copy_Ignore_Caller_ID_Name_State		menu_string_table[ 43 ]
#define ST_Copy_Ignore_Caller_ID_Name_States	menu_string_table[ 44 ]
#define ST_Copy_Ignore_Phone_Number_State		menu_string_table[ 45 ]
#define ST_Copy_Ignore_Phone_Number_States		menu_string_table[ 46 ]
#define ST_Copy_Job_Title						menu_string_table[ 47 ]
#define ST_Copy_Job_Titles						menu_string_table[ 48 ]
#define ST_Copy_Last_Called						menu_string_table[ 49 ]
#define ST_Copy_Last_Name						menu_string_table[ 50 ]
#define ST_Copy_Last_Names						menu_string_table[ 51 ]
#define ST_Copy_Match_Case_State				menu_string_table[ 52 ]
#define ST_Copy_Match_Case_States				menu_string_table[ 53 ]
#define ST_Copy_Match_Whole_Word_State			menu_string_table[ 54 ]
#define ST_Copy_Match_Whole_Word_States			menu_string_table[ 55 ]
#define ST_Copy_Nickname						menu_string_table[ 56 ]
#define ST_Copy_Nicknames						menu_string_table[ 57 ]
#define ST_Copy_Office_Phone_Number				menu_string_table[ 58 ]
#define ST_Copy_Office_Phone_Numbers			menu_string_table[ 59 ]
#define ST_Copy_Other_Phone_Number				menu_string_table[ 60 ]
#define ST_Copy_Other_Phone_Numbers				menu_string_table[ 61 ]
#define ST_Copy_Phone_Number					menu_string_table[ 62 ]
#define ST_Copy_Phone_Numbers					menu_string_table[ 63 ]
#define ST_Copy_Profession						menu_string_table[ 64 ]
#define ST_Copy_Professions						menu_string_table[ 65 ]
#define ST_Copy_Reference						menu_string_table[ 66 ]
#define ST_Copy_References						menu_string_table[ 67 ]
#define ST_Copy_Regular_Expression				menu_string_table[ 68 ]
#define ST_Copy_Regular_Expressions				menu_string_table[ 69 ]
#define ST_Copy_Selected						menu_string_table[ 70 ]
#define ST_Copy_Sent_to_Phone_Number			menu_string_table[ 71 ]
#define ST_Copy_Sent_to_Phone_Numbers			menu_string_table[ 72 ]
#define ST_Copy_Title							menu_string_table[ 73 ]
#define ST_Copy_Titles							menu_string_table[ 74 ]
#define ST_Copy_Total_Calls						menu_string_table[ 75 ]
#define ST_Copy_Web_Page						menu_string_table[ 76 ]
#define ST_Copy_Web_Pages						menu_string_table[ 77 ]
#define ST_Copy_Work_Phone_Number				menu_string_table[ 78 ]
#define ST_Copy_Work_Phone_Numbers				menu_string_table[ 79 ]
#define ST_E_xit								menu_string_table[ 80 ]
#define ST_Edit_Allow_Caller_ID_Name_List_Entry___	menu_string_table[ 81 ]
#define ST_Edit_Allow_Phone_Number_List_Entry___	menu_string_table[ 82 ]
#define ST_Edit_Contact___						menu_string_table[ 83 ]
#define ST_Edit_Ignore_Caller_ID_Name_List_Entry___	menu_string_table[ 84 ]
#define ST_Edit_Ignore_Phone_Number_List_Entry___	menu_string_table[ 85 ]
#define ST_Exit									menu_string_table[ 86 ]
#define ST_Export___							menu_string_table[ 87 ]
#define ST_Export_Contacts___					menu_string_table[ 88 ]
#define ST_Ignore_Incoming_Call					menu_string_table[ 89 ]
#define ST_Import___							menu_string_table[ 90 ]
#define ST_Import_Contacts___					menu_string_table[ 91 ]
#define ST_Open_VZ_Enhanced_56K					menu_string_table[ 92 ]
#define ST_Open_Web_Page						menu_string_table[ 93 ]
#define ST_Options___							menu_string_table[ 94 ]
#define ST_Remove_Contact						menu_string_table[ 95 ]
#define ST_Remove_from_Allow_Caller_ID_Name_List	menu_string_table[ 96 ]
#define ST_Remove_from_Allow_Phone_Number_List	menu_string_table[ 97 ]
#define ST_Remove_from_Ignore_Caller_ID_Name_List	menu_string_table[ 98 ]
#define ST_Remove_from_Ignore_Phone_Number_List	menu_string_table[ 99 ]
#define ST_Remove_Selected						menu_string_table[ 100 ]
#define ST_Search_with							menu_string_table[ 101 ]
#define ST_Select_All							menu_string_table[ 102 ]
#define ST_Send_Email___						menu_string_table[ 103 ]
#define ST_Tabs									menu_string_table[ 104 ]
#define ST_VZ_Enhanced_56K__Home_Page			menu_string_table[ 105 ]

extern wchar_t *search_with_string_table[];

#define ST_800Notes								search_with_string_table[ 0 ]
#define ST_Bing									search_with_string_table[ 1 ]
#define ST_Callerr								search_with_string_table[ 2 ]
#define ST_Google								search_with_string_table[ 3 ]
#define ST_Nomorobo								search_with_string_table[ 4 ]
#define ST_OkCaller								search_with_string_table[ 5 ]
#define ST_PhoneTray							search_with_string_table[ 6 ]
#define ST_WhitePages							search_with_string_table[ 7 ]
#define ST_WhoCallsMe							search_with_string_table[ 8 ]
#define ST_WhyCall_me							search_with_string_table[ 9 ]

extern wchar_t *options_string_table[];

#define ST_BTN___								options_string_table[ 0 ]
#define ST_12_hour								options_string_table[ 1 ]
#define ST_24_hour								options_string_table[ 2 ]
#define ST_Add_phone_number_to_Allow_PN_list	options_string_table[ 3 ]
#define ST_Add_phone_number_to_Ignore_PN_list	options_string_table[ 4 ]
#define ST_Always_on_top						options_string_table[ 5 ]
#define ST_Apply								options_string_table[ 6 ]
#define ST_Background_color_					options_string_table[ 7 ]
#define ST_Bottom_Left							options_string_table[ 8 ]
#define ST_Bottom_Right							options_string_table[ 9 ]
#define ST_Cancel								options_string_table[ 10 ]
#define ST_Center								options_string_table[ 11 ]
#define ST_Check_for_updates_upon_startup		options_string_table[ 12 ]
#define ST_Close_to_System_Tray					options_string_table[ 13 ]
#define ST_Default_modem_						options_string_table[ 14 ]
#define ST_Default_recording_					options_string_table[ 15 ]
#define ST_Default_ringtone_					options_string_table[ 16 ]
#define ST_Delay_Time__seconds__				options_string_table[ 17 ]
#define ST_Drop_answered_calls_after__seconds__	options_string_table[ 18 ]
#define ST_Enable_Call_Log_history				options_string_table[ 19 ]
#define ST_Enable_popup_windows_				options_string_table[ 20 ]
#define ST_Enable_ringtone_s_					options_string_table[ 21 ]
#define ST_Enable_System_Tray_icon_				options_string_table[ 22 ]
#define ST_Font_								options_string_table[ 23 ]
#define ST_Font_color_							options_string_table[ 24 ]
#define ST_Font_shadow_color_					options_string_table[ 25 ]
#define ST_General								options_string_table[ 26 ]
#define ST_Gradient_background_color_			options_string_table[ 27 ]
#define ST_Gradient_direction_					options_string_table[ 28 ]
#define ST_Height__pixels__						options_string_table[ 29 ]
#define ST_Hide_window_border					options_string_table[ 30 ]
#define ST_Horizontal							options_string_table[ 31 ]
#define ST_Justify_text_						options_string_table[ 32 ]
#define ST_Left									options_string_table[ 33 ]
#define ST_Log_events_to_Message_Log			options_string_table[ 34 ]
#define ST_Minimize_to_System_Tray				options_string_table[ 35 ]
#define ST_Modem								options_string_table[ 36 ]
#define ST_Play_recording_when_call_is_answered	options_string_table[ 37 ]
#define ST_Popup								options_string_table[ 38 ]
#define ST_Preview_Popup						options_string_table[ 39 ]
#define ST_Recordings_take_priority_if_longer_	options_string_table[ 40 ]
#define ST_Repeat_recording_					options_string_table[ 41 ]
#define ST_Retries_								options_string_table[ 42 ]
#define ST_Right								options_string_table[ 43 ]
#define ST_Screen_Position_						options_string_table[ 44 ]
#define ST_Show_contact_picture					options_string_table[ 45 ]
#define ST_Show_line_							options_string_table[ 46 ]
#define ST_Silent_startup						options_string_table[ 47 ]
#define ST_Time_format_							options_string_table[ 48 ]
#define ST_Top_Left								options_string_table[ 49 ]
#define ST_Top_Right							options_string_table[ 50 ]
#define ST_Transparency_						options_string_table[ 51 ]
#define ST_Vertical								options_string_table[ 52 ]
#define ST_When_call_is_allowed_by_its_CID_Name_	options_string_table[ 53 ]
#define ST_When_call_is_ignored_by_its_CID_Name_	options_string_table[ 54 ]
#define ST_Width__pixels__						options_string_table[ 55 ]

extern wchar_t *update_string_table[];

#define ST_A_new_version_is_available_		update_string_table[ 0 ]
#define ST_Checking_for_updates___			update_string_table[ 1 ]
#define ST_Checking_For_Updates___			update_string_table[ 2 ]
#define ST_Download_Complete				update_string_table[ 3 ]
#define ST_Download_Failed					update_string_table[ 4 ]
#define ST_Download_Update					update_string_table[ 5 ]
#define ST__DOWNLOAD_URL_					update_string_table[ 6 ]
#define ST_Downloading_the_update___		update_string_table[ 7 ]
#define ST_Downloading_Update___			update_string_table[ 8 ]
#define ST_Incomplete_Download				update_string_table[ 9 ]
#define ST__NOTES_							update_string_table[ 10 ]
#define ST_The_download_has_completed_		update_string_table[ 11 ]
#define ST_The_download_has_failed_			update_string_table[ 12 ]
#define ST_The_update_check_has_failed_		update_string_table[ 13 ]
#define ST_Up_To_Date						update_string_table[ 14 ]
#define ST_Update_Check_Failed				update_string_table[ 15 ]
#define ST__VERSION_						update_string_table[ 16 ]
#define ST_VZ_Enhanced_56K_is_up_to_date_	update_string_table[ 17 ]

extern wchar_t *connection_string_table[];

#define ST_A_connection_could_not_be_established		connection_string_table[ 0 ]
//#define ST_A_new_version_of_the_program_is_available	connection_string_table[ 1 ]
#define ST_Added_contact								connection_string_table[ 1 ]
//#define ST_Checking_for_updates						connection_string_table[ 2 ]
#define ST_Closed_connection							connection_string_table[ 2 ]
#define ST_Deleted_contact								connection_string_table[ 3 ]
//#define ST_Downloaded_update							connection_string_table[ 4 ]
//#define ST_Downloading_update							connection_string_table[ 5 ]
#define ST_File_could_not_be_saved						connection_string_table[ 4 ]
#define ST_Loaded_contact_list							connection_string_table[ 5 ]
#define ST_Received_incoming_caller_ID_information		connection_string_table[ 6 ]
#define ST_Reestablishing_connection					connection_string_table[ 7 ]
//#define ST_The_download_could_not_be_completed		connection_string_table[ 8 ]
//#define ST_The_program_is_up_to_date					connection_string_table[ 9 ]
//#define ST_The_update_check_could_not_be_completed	connection_string_table[ 10 ]
#define ST_Updated_contact_information					connection_string_table[ 8 ]

extern wchar_t *tapi_string_table[];

#define ST_Closing_line_device							tapi_string_table[ 0 ]
#define ST_Detecting_available_modems					tapi_string_table[ 1 ]
#define ST_Exiting_telephony_poll						tapi_string_table[ 2 ]
#define ST_Failed_to_initialize_telephony_interface		tapi_string_table[ 3 ]
#define ST_Initializing_telephony_interface				tapi_string_table[ 4 ]
#define ST_Opening_line_device							tapi_string_table[ 5 ]
#define ST_Shutting_down_telephony_interface			tapi_string_table[ 6 ]
#define ST_Waiting_for_incoming_calls					tapi_string_table[ 7 ]

extern wchar_t *list_string_table[];

#define ST_Added_caller_ID_name_to_allow_caller_ID_name_list		list_string_table[ 0 ]
#define ST_Added_caller_ID_name_s__to_allow_caller_ID_name_list		list_string_table[ 1 ]
#define ST_Added_caller_ID_name_to_ignore_caller_ID_name_list		list_string_table[ 2 ]
#define ST_Added_caller_ID_name_s__to_ignore_caller_ID_name_list	list_string_table[ 3 ]
#define ST_Added_phone_number_to_allow_phone_number_list			list_string_table[ 4 ]
#define ST_Added_phone_number_s__to_allow_phone_number_list			list_string_table[ 5 ]
#define ST_Added_phone_number_to_ignore_phone_number_list			list_string_table[ 6 ]
#define ST_Added_phone_number_s__to_ignore_phone_number_list		list_string_table[ 7 ]
#define ST_Automatic_save_has_completed						list_string_table[ 8 ]
#define ST_Exported_allow_caller_ID_name_list				list_string_table[ 9 ]
#define ST_Exported_allow_phone_number_list					list_string_table[ 10 ]
#define ST_Exported_call_log_history						list_string_table[ 11 ]
#define ST_Exported_contact_list							list_string_table[ 12 ]
#define ST_Exported_ignore_caller_ID_name_list				list_string_table[ 13 ]
#define ST_Exported_ignore_phone_number_list				list_string_table[ 14 ]
#define ST_Imported_allow_caller_ID_name_list				list_string_table[ 15 ]
#define ST_Imported_allow_phone_number_list					list_string_table[ 16 ]
#define ST_Imported_call_log_history						list_string_table[ 17 ]
#define ST_Imported_contact_list							list_string_table[ 18 ]
#define ST_Imported_ignore_caller_ID_name_list				list_string_table[ 19 ]
#define ST_Imported_ignore_phone_number_list				list_string_table[ 20 ]
#define ST_Loaded_allow_caller_ID_name_list					list_string_table[ 21 ]
#define ST_Loaded_allow_phone_number_list					list_string_table[ 22 ]
#define ST_Loaded_call_log_history							list_string_table[ 23 ]
#define ST_Loaded_ignore_caller_ID_name_list				list_string_table[ 24 ]
#define ST_Loaded_ignore_phone_number_list					list_string_table[ 25 ]
#define ST_Loaded_recording_directory						list_string_table[ 26 ]
#define ST_Loaded_ringtone_directory						list_string_table[ 27 ]
#define ST_Performing_automatic_save						list_string_table[ 28 ]
#define ST_Removed_caller_ID_name_s__from_allow_caller_ID_name_list	list_string_table[ 29 ]
#define ST_Removed_phone_number_s__from_allow_phone_number_list		list_string_table[ 30 ]
#define ST_Removed_call_log_entry___entries					list_string_table[ 31 ]
#define ST_Removed_caller_ID_name_s__from_ignore_caller_ID_name_list	list_string_table[ 32 ]
#define ST_Removed_phone_number_s__from_ignore_phone_number_list		list_string_table[ 33 ]
#define ST_Updated_allowed_caller_ID_name					list_string_table[ 34 ]
#define ST_Updated_allowed_caller_ID_name_s_call_count		list_string_table[ 35 ]
#define ST_Updated_allowed_phone_number						list_string_table[ 36 ]
#define ST_Updated_allowed_phone_number_s_call_count		list_string_table[ 37 ]
#define ST_Updated_ignored_caller_ID_name					list_string_table[ 38 ]
#define ST_Updated_ignored_caller_ID_name_s_call_count		list_string_table[ 39 ]
#define ST_Updated_ignored_phone_number						list_string_table[ 40 ]
#define ST_Updated_ignored_phone_number_s_call_count		list_string_table[ 41 ]

#endif
